-- Drop tables if they already exist for a clean slate
DROP TABLE IF EXISTS daily_checkins;
DROP TABLE IF EXISTS users;

-- Create a robust 'users' table with a hashed password for security
CREATE TABLE users (
    id TEXT PRIMARY KEY,
    username TEXT NOT NULL,
    email TEXT NOT NULL UNIQUE,
    -- Passwords should ALWAYS be stored as a secure hash, never plain text
    password_hash TEXT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Create the core table for the project: the daily check-in
-- This table will store the user's self-reported score (1-10) for each of the 8 wellness dimensions each day
CREATE TABLE daily_checkins (
    checkin_id INTEGER PRIMARY KEY AUTOINCREMENT,
    user_id TEXT NOT NULL,
    checkin_date DATE NOT NULL,
    
    -- The 8 Wellness Dimensions
    physical_score INTEGER CHECK(physical_score BETWEEN 1 AND 10),
    nutritional_score INTEGER CHECK(nutritional_score BETWEEN 1 AND 10),
    mental_score INTEGER CHECK(mental_score BETWEEN 1 AND 10),
    intellectual_score INTEGER CHECK(intellectual_score BETWEEN 1 AND 10),
    social_score INTEGER CHECK(social_score BETWEEN 1 AND 10),
    habitual_score INTEGER CHECK(habitual_score BETWEEN 1 AND 10),
    financial_score INTEGER CHECK(financial_score BETWEEN 1 AND 10),
    environmental_score INTEGER CHECK(environmental_score BETWEEN 1 AND 10),

    notes TEXT,
    
    -- Ensure a user can only have one check-in per day
    UNIQUE(user_id, checkin_date),
    FOREIGN KEY (user_id) REFERENCES users (id)
);

-- Insert sample data for a user.
-- NOTE: In a real app, the password_hash would be generated by the backend.
-- This is a placeholder for a securely hashed password for 'password123'.
INSERT INTO users (id, username, email, password_hash) VALUES
('user-alex-001', 'Alex', 'alex@university.edu', '$2b$12$EixZaYVK1fsJo3sW2yX5C.n.M5k2i6/wGPdeM5pPSkpgC22yS5nS6');

-- Insert some sample daily check-ins for Alex to demonstrate the instructional chart
INSERT INTO daily_checkins (user_id, checkin_date, physical_score, nutritional_score, mental_score, intellectual_score, social_score, habitual_score, financial_score, environmental_score, notes) VALUES
('user-alex-001', '2025-09-29', 7, 8, 5, 8, 7, 6, 8, 7, 'Start of a busy week.'),
('user-alex-001', '2025-09-30', 8, 7, 6, 7, 8, 7, 7, 8, 'Felt productive today.'),
('user-alex-001', '2025-10-01', 5, 5, 3, 4, 4, 4, 5, 6, 'Mid-term exam pressure is high. Ate junk food.'),
('user-alex-001', '2025-10-02', 7, 7, 6, 7, 7, 8, 6, 8, 'Finished my exam, feeling much better.');
